services:
  frontend:
    build: .
    restart: always
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/portfolio.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/thomas-tran.fr/fullchain.pem:/etc/letsencrypt/live/thomas-tran.fr/fullchain.pem:ro
      - /etc/letsencrypt/live/thomas-tran.fr/privkey.pem:/etc/letsencrypt/live/thomas-tran.fr/privkey.pem:ro
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge